#!/usr/bin/env php
<?php

use LaraGram\Console\Input\ArgvInput;

require_once __DIR__.'/vendor/autoload.php';

$status = (require_once __DIR__.'/bootstrap/app.php')
    ->handleCommand(new ArgvInput);

exit($status);
